name: All Checks

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lint-test:
    name: "Lint and Test"
    uses: ./.github/workflows/basic_checks.yml
    secrets: inherit

  # TODO uncomment when repo is public
  # espresso-tests:
    # name: "Espresso Tests"
    # uses: ./.github/workflows/espresso_tests.yml
    # secrets: inherit
