name: All Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lint-test:
    name: "Lint and Test"
    uses: ./.github/workflows/lint_test.yml
    secrets: inherit
    with:
      # testType: all
      testType: unit
