name: Basic Checks

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches-ignore:
    # runs on main as part of All Checks
    - main

env:
  USERNAME: ${{ secrets.USERNAME }}
  TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  lint:
    name: "Linting"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Java Version
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Linting
        run: ./gradlew ktlintCheck

  app-unit-tests:
    name: "Unit Tests (app module)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Java Version
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Tests
        run: ./gradlew :app:test --stacktrace

  customview-unit-tests:
    name: "Unit Tests (customview module)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Java Version
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Tests
        run: ./gradlew :customview:test --stacktrace
