name: Lint and Test

on:
  workflow_dispatch:
    inputs:
      testType:
        description: App Test Type
        default: unit
        type: choice
        options:
          - unit
          - robolectric
          - all
  workflow_call:
    inputs:
      testType:
        required: true
        default: all
        type: string
  pull_request:
#  push:
#    branches-ignore:
#    # runs on main as part of All Checks
#    - main

env:
  USERNAME: ${{ secrets.USERNAME }}
  TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  lint:
    name: "Linting"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Java Version
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 17

      - name: Linting
        run: ./gradlew ktlintCheck

  app-unit-tests:
    name: "Unit Tests (app module)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Java Version
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 17

      - name: Tests
        run: ./gradlew :app:test -PtestType=${{ inputs.testType || unit }} --stacktrace

  customview-unit-tests:
    name: "Unit Tests (customview module)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Java Version
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 17

      - name: Tests
        run: ./gradlew :customview:test --stacktrace
